/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package demo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jamiaharper
 */
public class GuestReservations extends javax.swing.JFrame {

    /** Creates new form GuestReservations */
    Connection con;
    PreparedStatement pts;
    ResultSet rs;
    String user;
    public GuestReservations() {
        initComponents();
    }
    public GuestReservations(String uname){
        initComponents();
        user = uname;
        show_res();
        show_room();
        
    }
    public ArrayList<Room> roomList(){
        ArrayList<Room> roomList = new ArrayList();
        ArrayList<String> roomN = new ArrayList();
        String num;
        try{
            con = Connections.getConnection();
            String query1 = "SELECT r_num FROM reservation WHERE guest_username='"+user+"'";
            Statement st = con.createStatement();
            rs = st.executeQuery(query1);
            while (rs.next()){
                roomN.add(rs.getString("r_num"));
            }
            int i;
            for(i = 0; i < roomN.size();i++){
                num = roomN.get(i);
                String query2 = "SELECT * FROM room WHERE r_num='"+num+"'";
                Statement st2 = con.createStatement();
                rs = st2.executeQuery(query2);
                Room room;
                while(rs.next()){
                    room = new Room(rs.getString("r_num"),rs.getString("r_name"),rs.getString("r_description"),rs.getInt("r_price"));
                    roomList.add(room);
                }
            }
            
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        return roomList;
    }
    public void show_room(){
        ArrayList<Room> list = roomList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_GRoom.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size();i++){
            row[0] = list.get(i).getRoomNum();
            row[1] = list.get(i).getRoomName();
            row[2] = list.get(i).getDescription();
            row[3] = list.get(i).getPrice();
            model.addRow(row);
            
        }
    }
    public ArrayList<Reservation> reservationList(){
        ArrayList<Reservation> reservationList = new ArrayList<>();
        try{
            con = Connections.getConnection();
            String query1 = "SELECT * FROM reservation WHERE guest_username='"+user+"'";
            Statement st = con.createStatement();
            rs = st.executeQuery(query1);
            Reservation reservation;
            while (rs.next()){
                reservation = new Reservation(rs.getString("res_num"),rs.getString("r_num"),rs.getString("checkin_date"),rs.getString("checkout_date"));
                reservationList.add(reservation);
            }
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        return reservationList;
        
    }
    public void show_res(){
        ArrayList<Reservation> list = reservationList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_GR.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size();i++){
            row[0] = list.get(i).getResnum();
            row[1] = list.get(i).getRoom();
            row[2] = list.get(i).getCheckinD();
            row[3] = list.get(i).getCheckout();
            model.addRow(row);
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_GR = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_GRoom = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Display_GR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation #", "Room #", "Check In", "Check Out"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_GR);
        if (jTable_Display_GR.getColumnModel().getColumnCount() > 0) {
            jTable_Display_GR.getColumnModel().getColumn(1).setPreferredWidth(20);
        }

        jTable_Display_GRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room #", "Name", "Description", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable_Display_GRoom);
        if (jTable_Display_GRoom.getColumnModel().getColumnCount() > 0) {
            jTable_Display_GRoom.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable_Display_GRoom.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTable_Display_GRoom.getColumnModel().getColumn(2).setPreferredWidth(350);
            jTable_Display_GRoom.getColumnModel().getColumn(3).setPreferredWidth(15);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Your Reservations");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Your Rooms");

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GuestPage gp = new GuestPage(user);
        gp.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestReservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Display_GR;
    private javax.swing.JTable jTable_Display_GRoom;
    // End of variables declaration//GEN-END:variables

}
