/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jamiaharper
 */
public class GuestBill extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pts;
    ResultSet rs;
    String user;
    public GuestBill() {
        initComponents();
    }
    public GuestBill(String uname) {
        initComponents();
        user = uname;
        show_bill();
        
    }
    public ArrayList<Bill> billList(){
        ArrayList<Bill> billList = new ArrayList();
        try{
            con = Connections.getConnection();
            String query1 = "SELECT * FROM bill WHERE guest_username='"+user+"'";
            Statement st = con.createStatement();
            rs = st.executeQuery(query1);
            Bill bill;
            while (rs.next()){
                bill = new Bill(rs.getString("res_num"), rs.getDouble("payment_amount"), rs.getString("cc_info"),rs.getString("paid_on"));
                billList.add(bill);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        return billList;
    }
    public void show_bill(){
        ArrayList<Bill> list = billList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Bills.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size();i++){
            row[0] = list.get(i).getResNum();
            row[1] = list.get(i).getPayDate();
            row[2] = list.get(i).getAmount();
            row[3] = list.get(i).getCC();
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Bills = new javax.swing.JTable();
        goBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cc_info = new javax.swing.JTextField();
        UpdateCC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("       Your Bills");

        jTable_Display_Bills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation #", "Pay Date", "Cost", "CC #"
            }
        ));
        jTable_Display_Bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_BillsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Bills);

        goBack.setText("Go Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        jLabel2.setText("CC #:");

        cc_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc_infoActionPerformed(evt);
            }
        });

        UpdateCC.setText("Update CC#");
        UpdateCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goBack)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cc_info, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UpdateCC))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cc_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateCC)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        GuestPage gp = new GuestPage(user);
        gp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_goBackActionPerformed

    private void cc_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cc_infoActionPerformed

    private void UpdateCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCCActionPerformed
        // TODO add your handling code here:
        try{
            con = Connections.getConnection();
            String query = "UPDATE guest SET cc_info = ? WHERE g_username ='"+user+"'";
            String query2 = "UPDATE bill SET cc_info = ? WHERE guest_username ='"+user+"'";
            pts = con.prepareStatement(query);
            PreparedStatement billInfo = con.prepareStatement(query2);
            pts.setString(1, cc_info.getText());
            billInfo.setString(1,cc_info.getText());
            pts.executeUpdate();
            billInfo.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_Bills.getModel();
            model.setRowCount(0);
            show_bill();
            JOptionPane.showMessageDialog(null, "Update Guest CC_Info and Bill Information!");
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateCCActionPerformed

    private void jTable_Display_BillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_BillsMouseClicked
        // TODO add your handling code here:
        int i = jTable_Display_Bills.getSelectedRow();
        TableModel model = jTable_Display_Bills.getModel();
        cc_info.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTable_Display_BillsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateCC;
    private javax.swing.JTextField cc_info;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Bills;
    // End of variables declaration//GEN-END:variables
}
/*con = Connections.getConnection();
            String query = "UPDATE guest SET cc_info = ? WHERE g_username ='"+user+"'";
            String query2 = "UPDATE bill SET cc_info = ? WHERE g_username ='"+user+"'";
            pts = con.prepareStatement(query);
            PreparedStatement billInfo = con.prepareStatement(query2);
            pts.setString(1, cc_info.getText());
            billInfo.setString(1,cc_info.getText());
            pts.executeUpdate();
            billInfo.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_Bills.getModel();
            model.setRowCount(0);
            show_bill();
            JOptionPane.showMessageDialog(null, "Update Guest CC_Info and Bill Information!");*/