/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.sql.DriverManager;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jamiaharper
 */
public class RoomPage extends javax.swing.JFrame {

    /**
     * Creates new form RoomPage
     */
    public RoomPage() {
        initComponents();
        show_room();
    }
    public ArrayList<Room> roomList(){
        ArrayList<Room> roomList = new ArrayList<>();
        try{
            Class.forName(("com.mysql.jdbc.Driver"));
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/random", "root","miamiamia19");
            String query1 = "SELECT * FROM room";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            Room room;
            while (rs.next()){
                room = new Room(rs.getString("r_num"),rs.getString("c_Ssn"),rs.getString("r_description"),rs.getInt("r_price"),rs.getInt("r_beds"),rs.getInt("r_capacity"),rs.getString("r_name"),rs.getInt("r_floor"),rs.getBoolean("r_available"));
                roomList.add(room);
            }
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        return roomList;
        
    }
    public void show_room(){
        ArrayList<Room> list = roomList();
        DefaultTableModel model = (DefaultTableModel)jTable1_Display_Rooms.getModel();
        Object[] row = new Object[9];
        for (int i = 0; i < list.size();i++){
            row[0] = list.get(i).getRoomNum();
            row[1] = list.get(i).getCleaner();
            row[2] = list.get(i).getDescription();
            row[3] = list.get(i).getPrice();
            row[4] = list.get(i).getBeds();
            row[5] = list.get(i).getCapacity();
            row[6] = list.get(i).getRoomName();
            row[7] = list.get(i).getFloor();
            row[8] = list.get(i).isAvailable();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display_Rooms = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1_Display_Rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room #", "HouseKeeper", "Description", "Price", "Num Beds", "Capacity", "Name", "Floor", "Available"
            }
        ));
        jScrollPane1.setViewportView(jTable1_Display_Rooms);
        if (jTable1_Display_Rooms.getColumnModel().getColumnCount() > 0) {
            jTable1_Display_Rooms.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1_Display_Rooms.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTable1_Display_Rooms.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1_Display_Rooms.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable1_Display_Rooms.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTable1_Display_Rooms.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable1_Display_Rooms.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReceptionistPage rp = new ReceptionistPage();
        rp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display_Rooms;
    // End of variables declaration//GEN-END:variables
}
